apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-clean-operator-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/lwolf/kube-cleanup-operator.git'
    targetRevision: master
    path: deploy/helm/kube-cleanup-operator
    helm:
      releaseName: kube-clean-operator
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=background
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
