apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector-app
spec:
  project: cluster
  source:
    repoURL: https://github.com/emberstack/kubernetes-reflector.git
    path: src/helm/reflector
    targetRevision: v9.0.322
    helm:
      releaseName: reflector
      values: |
        replicaCount: 1
        image:
          repository: docker.io/emberstack/kubernetes-reflector
          pullPolicy: IfNotPresent
        namespaceOverride: "kube-system"
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        configuration:
          kubernetes:
            skipTlsVerify: true
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Prune=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
