apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 1.0.38
    helm:
      releaseName: reloader
      values: |
        kubernetes:
          host: https://kubernetes.default
        reloader:
          isArgoRollouts: true
          isOpenshift: false
          ignoreSecrets: false
          ignoreConfigMaps: false
          reloadOnCreate: true
          reloadStrategy: default
          ignoreNamespaces: ""
          logFormat: ""
          watchGlobally: true
          readOnlyRootFileSystem: false
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Prune=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
