apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ephemeral
spec:
  generators:
    - pullRequest:
        github:
          owner: skudasov
          repo: local-gitops
          tokenRef:
            secretName: github-token
            key: token
          labels:
            - preview
        requeueAfterSeconds: 60
  template:
    metadata:
      name: ephemeral-env
    spec:
      source:
        repoURL: 'https://github.com/skudasov/local-gitops'
        path: apps/target/ephemeral
      project: ephemeral
      destination:
        namespace: ephemeral
        server: https://kubernetes.default.svc