apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: core
  source:
    repoURL: 'https://github.com/bitnami/charts.git'
    targetRevision: 11.3.8
    chart: nginx-ingress-controller
    helm:
      releaseName: nginx
      values: |
        extraArgs:
          default-ssl-certificate: "kube-system/tls-secret"
          ingress-class: nginx
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Prune=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
