apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: core
  source:
    repoURL: 'https://github.com/bitnami/charts.git'
    targetRevision: HEAD
    path: bitnami/nginx-ingress-controller
    helm:
      releaseName: nginx
      parameters:
      - name: "default-ssl-certificate"
        value: "ingress/nginx-server-certs"
      - name: "tcpConfigMapNamespace"
        value: "development"
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Prune=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
