apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: core
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx.git
    targetRevision: ingress-nginx-3.15.2
    path: deploy/static/provider/kind
    kustomize:
      namespace: ingress-controller
      replicas:
      - name: ingress-nginx-controller
        count: 1
      patches:
        - target:
            kind: Deployment
            name: ingress-nginx-controller
          patch: |-
            - op: remove
              path: /spec/template/spec/tolerations
            - op: remove
              path: /spec/template/spec/nodeSelector
            - op: replace
              path: /spec/strategy
              value:
                type: Recreate
            - op: add
              path: /spec/template/spec/containers/0/args
              value:
                - /nginx-ingress-controller
                - --default-ssl-certificate=ingress-controller/tls
                - --ingress-class=nginx
                - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
                - --validating-webhook=:8443
                - --validating-webhook-certificate=/usr/local/certificates/cert
                - --validating-webhook-key=/usr/local/certificates/key
  destination:
    namespace: ingress-controller
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Prune=true
    - ServerSideApply=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
  ignoreDifferences:
  - group: ""
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-controller
    jsonPointers:
    - /spec/ports/0/nodePort
    - /spec/ports/1/nodePort