apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: core
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx.git
    targetRevision: controller-v1.12.1
    path: deploy/static/provider/kind
    kustomize:
      namespace: kube-system
      replicas:
      - name: ingress-nginx-controller
        count: 1
      patches:
        - target:
            kind: Deployment
            name: ingress-nginx-controller
          patch: |-
            - op: remove
              path: /spec/template/spec/tolerations
            - op: remove
              path: /spec/template/spec/nodeSelector
            - op: replace
              path: /spec/strategy
              value:
                type: Recreate
            - op: add
              path: /spec/template/spec/containers/0/args
              value:
                - /nginx-ingress-controller
                - --default-ssl-certificate=kube-system/tls-secret
                - --ingress-class=nginx
                - --validating-webhook=:8443
                - --election-id=ingress-nginx-leader
                - --controller-class=k8s.io/ingress-nginx
                - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
                - --validating-webhook=:8443
                - --validating-webhook-certificate=/usr/local/certificates/cert
                - --validating-webhook-key=/usr/local/certificates/key
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Prune=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
