apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: minimal-db
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  additionalVolumes:
    - name: data
      mountPath: /home/postgres/pgdata/partitions
      targetContainers:
        - postgres
      volumeSource:
        persistentVolumeClaim:
          claimName: local-path-pvc
          readyOnly: false
  resources:
    requests:
      cpu: 200m
      memory: 250Mi
    limits:
      cpu: 3200m
      memory: 500Mi
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "14"
