apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- svc.yaml
- github.com/rancher/local-path-provisioner/examples/pvc

namespace: example
nameSuffix: "-example"

commonAnnotations:
  argocd.argoproj.io/sync-wave: "4"

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    cluster.app: example
    app.kubernetes.io/part-of: example
