apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
  labels:
    app: whoami
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: whoami
  type: ClusterIP
