apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster
spec:
  description: Cluster-wide project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
