apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ephemeral
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Applications Example Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: ephemeral
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false