version: '3'
silent: true
env:
  VAULT_ADDR: "https://vault.k8s.localhost"
  VAULT_SKIP_VERIFY: "true"
  HOSTCTL: 1.1.4

tasks:
  default:
    cmds:
    - task: mkcert
    - task: kustomize
    - task: k3d
    - task: kubectl
    - task: jq
    - task: vault
    - task: hostctl

  mkcert:
    cmds:
    - echo -e "Installing mkcert"
    - choco install mkcert
    ignore_error: true

  kustomize:
    cmds:
    - echo -e "Installing kustomize"
    - choco install kustomize

  k3d:
    cmds:
    - echo -e "Installing k3d"
    - choco install k3d

  kubectl:
    cmds:
    - echo -e "Installing kubectl"
    - choco install kubernetes-cli

  jq:
    cmds:
    - echo -e "Installing jq"
    - choco install jq

  hostctl:
    cmds:
    - |
      echo -e "Installing hostctl"
      choco install wget && \
      cd utilities && \
      wget https://github.com/guumaster/hostctl/releases/download/v$HOSTCTL/hostctl_${HOSTCTL}_windows_64-bit.zip &&\
      unzip hostctl_${HOSTCTL}_windows_64-bit.zip && \
      rm hostctl_${HOSTCTL}_windows_64-bit.zip LICENSE README.md

  vault:
    cmds:
    - |
      echo -e "Installing Vault CLI" && \
      {{if eq OS "windows"}}choco install vault \
      {{else}}brew tap hashicorp/tap && brew install hashicorp/tap/vault{{end}}
