apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: 'https://github.com/gruberdev/local-gitops.git'
    path: apps/template
    targetRevision: main
  destination:
    namespace: development
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 35s
        factor: 2
        maxDuration: 15m
