apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: template-app
spec:
  project: apps
  source:
    repoURL: 'https://github.com/gruberdev/local-gitops.git'
    path: apps/template
    targetRevision: main
  destination:
    namespace: development
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Prune=true
    - ServerSideApply=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
