name: Validate Kubernetes Resources
on: push
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check if Services have changed
      id: changed-services
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          apps/**/svc.yaml
          apps/**/*-svc.yaml
    - name: Check if Deployments/Statefulsets have changed
      id: changed-workloads
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          apps/**/deployment.yaml
          apps/**/statefulset.yaml
    - name: Check if configMap/Secrets have changed
      id: changed-configs
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          apps/**/cm.yaml
          apps/**/secret.yaml
    - name: Check if Permissions have changed
      id: changed-rbac
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          apps/**/rb.yaml
          apps/**/crb.yaml
          apps/**/role.yaml
          apps/**/cr.yaml
    - name: Check if Storage resources have changed
      id: changed-storage
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          apps/**/pvc.yaml
          apps/**/class.yaml
          apps/**/pv.yaml
    - name: Install Kubeconform
      run: |
        (wget -qO- https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz | sudo tar xvz -C /usr/bin) && sudo chmod +x /usr/bin/kubeconform
    - name: Validate new Services
      id: validate-service
      uses: mathiasvr/command-output@v1
      if: steps.changed-services.outputs.any_changed == 'true'
      with:
        run: |
          find . -maxdepth 15 -name svc.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;

    - name: Validate new Workloads
      id: validate-workloads
      uses: mathiasvr/command-output@v1
      if: steps.changed-workloads.outputs.any_changed == 'true'
      with:
        run: |
          find . -maxdepth 15 -name deployment.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
          find . -maxdepth 15 -name statefulset.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;

    - name: Validate new configMaps or Secrets
      id: validate-configs-cm
      uses: mathiasvr/command-output@v1
      if: steps.changed-configs.outputs.any_changed == 'true'
      with:
        run: |
          find . -maxdepth 15 -name cm.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
          find . -maxdepth 15 -name secret.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;

    - name: Validate new Permissions and RBAC resources
      id: validate-configs-rbac
      uses: mathiasvr/command-output@v1
      if: steps.changed-rbac.outputs.any_changed == 'true'
      with:
        run: |
          find . -maxdepth 15 -name rb.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
          find . -maxdepth 15 -name crb.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
          find . -maxdepth 15 -name role.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
          find . -maxdepth 15 -name cr.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;

    - name: Validate new Storage resources
      id: validate-configs
      uses: mathiasvr/command-output@v1
      if: steps.changed-storage.outputs.any_changed == 'true'
      with:
        run: |
          find . -maxdepth 15 -name pvc.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
          find . -maxdepth 15 -name pv.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
          find . -maxdepth 15 -name clas.yaml -exec kubeconform --verbose -exit-on-error -ignore-missing-schemas -kubernetes-version "1.26.0" -schema-location default {} \;
